version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    networks:
      - soa-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  migrations:
    image: python:3.10
    environment:
      - USERS_DB_URL=mysql://root:password@mysql:3306/users_db
    networks:
      - soa-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./users:/app
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt
      && cd src/db
      && alembic upgrade head"

  users:
    image: python:3.10
    environment:
      - USERS_DB_URL=mysql://root:password@mysql:3306/users_db
      - USERS_SERVER_HOST=0.0.0.0
      - USERS_SERVER_PORT=8080
    networks:
      - soa-network
    ports:
      - "8080:8080"
    depends_on:
      - migrations
    volumes:
      - ./users:/app
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt
      && cd src
      && python3 main.py"

networks:
  soa-network:
    name: "soa-network"